on Exd(a,b,c,d,e,f,h){ow.call(this,h);this.aa=[a,b,c,d];Fxd(this.aa);this.xa=e;this.Ca=f;this.Aa=this.ea=this.ga=this.ha=this.ia=null}z(Exd,ow);
Exd.prototype.jb=function(){this.Bc(Np(Cxd,{},void 0,this.Oa()));this.ia=this.Va("docs-material-rgba-red-input");this.ha=this.Va("docs-material-rgba-green-input");this.ga=this.Va("docs-material-rgba-blue-input");this.ea=this.Va("docs-material-rgba-alpha-input");this.Aa=this.Va("docs-material-rgba-alpha-wrapper");this.Ca?this.xa||to(this.Aa,"visibility","hidden"):Jo(this.Aa,this.xa)};
Exd.prototype.ob=function(){var a=this;Gxd(this);this.getHandler().listen(this.ia,"keyup",this.ua).listen(this.ha,"keyup",this.ua).listen(this.ga,"keyup",this.ua).listen(this.ia,"blur",function(){return void Hxd(a,Ixd,a.ia)}).listen(this.ha,"blur",function(){return Hxd(a,Ixd,a.ha)}).listen(this.ga,"blur",function(){return Hxd(a,Ixd,a.ga)});this.xa&&this.getHandler().listen(this.ea,"keyup",this.ua).listen(this.ea,"blur",function(){return Hxd(a,Jxd,a.ea)})};
Exd.prototype.ua=function(){var a=[Number(this.ia.value),Number(this.ha.value),Number(this.ga.value),Number(this.ea.value)/100];Fxd(a)&&(this.aa=a,this.dispatchEvent("Yc"))};function Gxd(a){a.ia.value&&a.aa[0]==a.ia.value||(a.ia.value=a.aa[0]);a.ha.value&&a.aa[1]==a.ha.value||(a.ha.value=a.aa[1]);a.ga.value&&a.aa[2]==a.ga.value||(a.ga.value=a.aa[2]);var b=Math.round(100*a.aa[3]);a.ea.value&&b==a.ea.value||(a.ea.value=b)}function Fxd(a){return ny("("+a[0]+", "+a[1]+", "+a[2]+")")&&Jxd(a[3])}
function Hxd(a,b,c){Ma(c.value)&&(c.value=0);b(c===a.ea?Number(c.value)/100:Number(c.value))||Gxd(a)}function Ixd(a){return!isNaN(a)&&$Na(new kr(0,255),a)}function Jxd(a){return!isNaN(a)&&$Na(new kr(0,1),a)};function Kxd(a,b,c,d){d=void 0===d?"#fff":d;qx.call(this,a);this.ia=c/2+2;this.Aa=b;dw(a,"docs-material-color-picker-dragger");Co(a,new fn(c,c));a=d;ny(a);this.target.style.backgroundColor=a;a=this.Aa.getBoundingClientRect();rx(this,new ro(-this.ia,-this.ia,a.width,a.height))}z(Kxd,qx);function Lxd(a){var b=bn(a.deltaX+a.ia,0,a.Aa.getBoundingClientRect().width);a=bn(a.deltaY+a.ia,0,a.Aa.getBoundingClientRect().height);return new dn(b,a)}
Kxd.prototype.setPosition=function(a,b){a=bn(a,0,1);b=bn(b,0,1);this.deltaX=a*this.Aa.getBoundingClientRect().width-this.ia;this.deltaY=b*this.Aa.getBoundingClientRect().height-this.ia;this.target.style.top=this.deltaY+"px";this.target.style.left=this.deltaX+"px"};function Mxd(){return tp('<div class="docs-material-color-picker-saturation-value" tabindex="0" role="slider"><div class="docs-material-color-picker-saturation-value-dragger"> </div><div class="docs-material-color-picker-saturation-value-background docs-material-color-picker-overlay"></div><div class="docs-material-color-picker-saturation-overlay docs-material-color-picker-overlay"></div><div class="docs-material-color-picker-value-overlay docs-material-color-picker-overlay"></div></div>')};function Nxd(a,b){ow.call(this,b);this.aa=[a,1,255];this.Af=null}z(Nxd,ow);u=Nxd.prototype;u.jb=function(){this.Bc(Np(Mxd,{},void 0,this.Oa()))};u.ob=function(){var a=this.rb(),b=this.Oa().Va("docs-material-color-picker-saturation-value-dragger",a);this.Af=new Kxd(b,a,16);this.Na(this.Af);Oxd(this);this.getHandler().listen(this.Af,"drag",this.vDc).listen(a,"mousedown",this.xDc).listen(this.getElement(),"keydown",this.wDc).listen(this.getElement(),["keyup","mouseup"],this.wzd)};
function Oxd(a){a.Va("docs-material-color-picker-saturation-value-background").style.backgroundColor=my(qlc(a.aa[0],1,255));a.Af.setPosition(a.aa[1],1-a.aa[2]/255);Pxd(a)}function Pxd(a){var b=a.Af;a=my(qlc(a.aa[0],a.aa[1],a.aa[2]));ny(a);b.target.style.backgroundColor=a}u.vDc=function(a){Qxd(this,a.clientX,a.clientY)};
u.wDc=function(a){if(38==a.keyCode||40==a.keyCode||37==a.keyCode||39==a.keyCode){var b=Lxd(this.Af).x+this.rb().getBoundingClientRect().left,c=Lxd(this.Af).y+this.rb().getBoundingClientRect().top,d=a.shiftKey?10:1;38==a.keyCode?c-=d:40==a.keyCode?c+=d:37==a.keyCode?b-=d:39==a.keyCode&&(b+=d);Qxd(this,b,c);a.preventDefault();a.stopPropagation()}};u.wzd=function(){var a="Colour "+my(qlc(this.aa[0],this.aa[1],this.aa[2]));Yv(this.rb(),"valuetext",a);this.getElement().focus()};
u.xDc=function(a){Qxd(this,a.clientX,a.clientY);this.Af.xaa(a)};function Qxd(a,b,c){var d=a.rb().getBoundingClientRect();a.aa[1]=bn(b-d.left,0,d.width)/d.width;a.aa[2]=255*(1-bn(c-d.top,0,d.height)/d.height);Pxd(a);a.dispatchEvent("Zc")};function Rxd(a,b,c,d,e,f){c=void 0===c?!1:c;d=void 0===d?"#ffffff":d;e=void 0===e?1:e;ow.call(this,f);ny(d);this.ga=a;this.ha=c;this.hb=b;this.aa=Swd(d);this.ia=rlc(oy(d));this.ea=e;this.Ha=new Ywd(ok(this.ga,"docs-ecprgba")?32:20,d);this.lb(this.Ha);this.Ka=new Nxd(this.ia[0]);this.lb(this.Ka);this.Da=new Axd;this.lb(this.Da);this.xa=new Bxd(this.aa);this.lb(this.xa);(this.Aa=(this.La=ok(this.ga,"docs-ecprgba")&&ok(this.ga,"docs-ecped")&&window.EyeDropper?new window.EyeDropper:null)?new qA(Mp(Op,
{icon:"docs-icon-img docs-icon-colorize-24",NS:"docs-material"})):null)&&this.lb(this.Aa);this.Ia=new Sq;this.Na(this.Ia);this.Ca=null;ok(this.ga,"docs-ecprgba")&&(a=oy(this.aa),this.Ca=new Exd(a[0],a[1],a[2],this.ea,this.ha,!!this.La),this.lb(this.Ca));this.Ua=new Set;this.bb=this.ua=null}z(Rxd,ow);u=Rxd.prototype;
u.jb=function(){this.Bc(Np($wd,{Mad:ok(this.ga,"docs-ecprgba"),Uad:!!this.La},void 0,this.Oa()));this.Ka.render(this.Va("docs-material-hsv-color-picker-saturation-value"));this.Ha.render(this.Va("docs-material-hsv-color-picker-swatch"));this.Da.render(this.Va("docs-material-hsv-color-picker-hue-slider"));this.xa.render(this.Va("docs-material-hsv-color-picker-opacity-slider"));ok(this.ga,"docs-ecprgba")&&this.Ca.render(this.Va("docs-material-hsv-color-picker-rgba-inputs"));this.ua=this.Va("docs-material-hsv-color-picker-input");
this.bb=this.Va(ok(this.ga,"docs-ecprgba")?"docs-material-hsv-color-picker-opacity-slider":"docs-material-hsv-color-picker-opacity-wrapper");this.Aa&&(this.Aa.render(this.Va("docs-material-hsv-color-picker-eyedropper")),zw(this.Aa.rb(),"Pick a custom colour"))};
u.ob=function(){ow.prototype.ob.call(this);Sxd(this);Txd(this);var a=this.ha;this.ha=a;Jo(this.bb,a);ok(this.ga,"docs-ecprgba")&&!a&&(Do(this.ua,75),this.ua.maxLength=7);this.getHandler().listen(this.ua,"keyup",this.byd).listen(this.ua,"blur",this.yDc).listen(this.Ka,"Zc",this.FHd).listen(this.Da,"Xc",this.xyd).listen(this.xa,"Xc",this.sDd);this.Aa&&this.getHandler().listen(this.Aa,"action",this.Xvd);ok(this.ga,"docs-ecprgba")&&this.getHandler().listen(this.Ca,"Yc",this.mHd)};u.Vc=m("aa");
u.getOpacity=function(){return this.ha?this.ea:1};function Uxd(a,b){ny(b);b=Swd(b);if(b!=a.aa||ok(a.ga,"docs-ecprgba"))a.aa=b,a.ia=rlc(oy(b)),Vxd(a)}u.FHd=function(){this.ia=this.Ka.aa;this.aa=tlc(this.ia);Vxd(this,4)};u.xyd=function(){this.ia[0]!=this.Da.getValue()&&(this.ia[0]=this.Da.getValue(),this.aa=tlc(this.ia),Vxd(this,3))};
u.sDd=function(){if(ok(this.ga,"docs-ecprgba"))this.ea!=this.xa.getValue()&&(this.ea=this.xa.getValue(),Txd(this,5));else{this.ea=this.xa.get